% Autogenerated file: Wed Jan 17 07:21:29 2018
function writeCodeInfoFcn


% Load a ComponentInterface object from IR
codeIRInfoStruct = load('C:\Sumpurn\Projects\slexMulticoreExample_grt_rtw\tlc\codeIRInfo.mat');
codeInfo = codeIRInfoStruct.codeInfo;




skippedParameters = [];

  tmpParams = [];
if ~isempty(tmpParams)
codeInfo.Parameters = [codeInfo.Parameters, tmpParams'];
end

    tmpArgs         = [];
tmpActualArgs   = [];
tmpRet          = coder.types.Argument.empty;
tmpActualReturn = RTW.DataInterface.empty;
  

  Initialize_Prototype = coder.types.Prototype;
  Initialize_Prototype.Arguments  = tmpArgs;
  Initialize_Prototype.Return     = tmpRet;
    Initialize_Prototype.HeaderFile = ['slexMulticoreExample', '.h'];
  Initialize_Prototype.SourceFile = ['slexMulticoreExample', '.c'];

  Initialize_Interface = RTW.FunctionInterface;
  Initialize_Interface.Prototype    = Initialize_Prototype;
  Initialize_Interface.ActualArgs   = tmpActualArgs;
  Initialize_Interface.ActualReturn = tmpActualReturn;

      Initialize_Prototype.Name = 'slexMulticoreExample_initialize';
  time_constant = codeInfo.TimingProperties(getIndexFromTimingInternalId(codeInfo.TimingInternalIds, -1));
      Initialize_Interface.Timing = time_constant;
      codeInfo.InitializeFunctions =  [codeInfo.InitializeFunctions, Initialize_Interface'];

        
    
          tmpArgs         = [];
  tmpActualArgs   = [];
  tmpRet          = coder.types.Argument.empty;
  tmpActualReturn = RTW.DataInterface.empty;
  
  
  Core1_Task1_output_Prototype            = coder.types.Prototype;
  Core1_Task1_output_Prototype.Arguments  = tmpArgs;
  Core1_Task1_output_Prototype.Return     = tmpRet;
  Core1_Task1_output_Prototype.HeaderFile = ['slexMulticoreExample', '.h'];
  Core1_Task1_output_Prototype.SourceFile = ['slexMulticoreExample', '.c'];
  
  Core1_Task1_output_Interface              = RTW.FunctionInterface;
  Core1_Task1_output_Interface.Prototype    = Core1_Task1_output_Prototype;
  Core1_Task1_output_Interface.ActualArgs   = tmpActualArgs;
  Core1_Task1_output_Interface.ActualReturn = tmpActualReturn;
  
  Core1_Task1_output_Prototype.Name = 'Core1_Task1_output'; 
  time_0 = codeInfo.TimingProperties(getIndexFromTimingInternalId(codeInfo.TimingInternalIds, 0));
  Core1_Task1_output_Interface.Timing = time_0;
  
      codeInfo.OutputFunctions =  [codeInfo.OutputFunctions, Core1_Task1_output_Interface];
  
;
   
            tmpArgs         = [];
  tmpActualArgs   = [];
  tmpRet          = coder.types.Argument.empty;
  tmpActualReturn = RTW.DataInterface.empty;
  
  
  Core1_Task1_update_Prototype            = coder.types.Prototype;
  Core1_Task1_update_Prototype.Arguments  = tmpArgs;
  Core1_Task1_update_Prototype.Return     = tmpRet;
  Core1_Task1_update_Prototype.HeaderFile = ['slexMulticoreExample', '.h'];
  Core1_Task1_update_Prototype.SourceFile = ['slexMulticoreExample', '.c'];
  
  Core1_Task1_update_Interface              = RTW.FunctionInterface;
  Core1_Task1_update_Interface.Prototype    = Core1_Task1_update_Prototype;
  Core1_Task1_update_Interface.ActualArgs   = tmpActualArgs;
  Core1_Task1_update_Interface.ActualReturn = tmpActualReturn;
  
  Core1_Task1_update_Prototype.Name = 'Core1_Task1_update'; 
  time_0 = codeInfo.TimingProperties(getIndexFromTimingInternalId(codeInfo.TimingInternalIds, 0));
  Core1_Task1_update_Interface.Timing = time_0;
  
      codeInfo.UpdateFunctions =  [codeInfo.UpdateFunctions, Core1_Task1_update_Interface];
  
;
          tmpArgs         = [];
  tmpActualArgs   = [];
  tmpRet          = coder.types.Argument.empty;
  tmpActualReturn = RTW.DataInterface.empty;
  
  
  Core1_Task2_output_Prototype            = coder.types.Prototype;
  Core1_Task2_output_Prototype.Arguments  = tmpArgs;
  Core1_Task2_output_Prototype.Return     = tmpRet;
  Core1_Task2_output_Prototype.HeaderFile = ['slexMulticoreExample', '.h'];
  Core1_Task2_output_Prototype.SourceFile = ['slexMulticoreExample', '.c'];
  
  Core1_Task2_output_Interface              = RTW.FunctionInterface;
  Core1_Task2_output_Interface.Prototype    = Core1_Task2_output_Prototype;
  Core1_Task2_output_Interface.ActualArgs   = tmpActualArgs;
  Core1_Task2_output_Interface.ActualReturn = tmpActualReturn;
  
  Core1_Task2_output_Prototype.Name = 'Core1_Task2_output'; 
  time_0 = codeInfo.TimingProperties(getIndexFromTimingInternalId(codeInfo.TimingInternalIds, 0));
  Core1_Task2_output_Interface.Timing = time_0;
  
      codeInfo.OutputFunctions =  [codeInfo.OutputFunctions, Core1_Task2_output_Interface];
  
;
   
    
    
    
          tmpArgs         = [];
  tmpActualArgs   = [];
  tmpRet          = coder.types.Argument.empty;
  tmpActualReturn = RTW.DataInterface.empty;
  
  
  Core2_Task3_output_Prototype            = coder.types.Prototype;
  Core2_Task3_output_Prototype.Arguments  = tmpArgs;
  Core2_Task3_output_Prototype.Return     = tmpRet;
  Core2_Task3_output_Prototype.HeaderFile = ['slexMulticoreExample', '.h'];
  Core2_Task3_output_Prototype.SourceFile = ['slexMulticoreExample', '.c'];
  
  Core2_Task3_output_Interface              = RTW.FunctionInterface;
  Core2_Task3_output_Interface.Prototype    = Core2_Task3_output_Prototype;
  Core2_Task3_output_Interface.ActualArgs   = tmpActualArgs;
  Core2_Task3_output_Interface.ActualReturn = tmpActualReturn;
  
  Core2_Task3_output_Prototype.Name = 'Core2_Task3_output'; 
  time_1 = codeInfo.TimingProperties(getIndexFromTimingInternalId(codeInfo.TimingInternalIds, 1));
  Core2_Task3_output_Interface.Timing = time_1;
  
      codeInfo.OutputFunctions =  [codeInfo.OutputFunctions, Core2_Task3_output_Interface];
  
;
   
            tmpArgs         = [];
  tmpActualArgs   = [];
  tmpRet          = coder.types.Argument.empty;
  tmpActualReturn = RTW.DataInterface.empty;
  
  
  Core2_Task3_update_Prototype            = coder.types.Prototype;
  Core2_Task3_update_Prototype.Arguments  = tmpArgs;
  Core2_Task3_update_Prototype.Return     = tmpRet;
  Core2_Task3_update_Prototype.HeaderFile = ['slexMulticoreExample', '.h'];
  Core2_Task3_update_Prototype.SourceFile = ['slexMulticoreExample', '.c'];
  
  Core2_Task3_update_Interface              = RTW.FunctionInterface;
  Core2_Task3_update_Interface.Prototype    = Core2_Task3_update_Prototype;
  Core2_Task3_update_Interface.ActualArgs   = tmpActualArgs;
  Core2_Task3_update_Interface.ActualReturn = tmpActualReturn;
  
  Core2_Task3_update_Prototype.Name = 'Core2_Task3_update'; 
  time_1 = codeInfo.TimingProperties(getIndexFromTimingInternalId(codeInfo.TimingInternalIds, 1));
  Core2_Task3_update_Interface.Timing = time_1;
  
      codeInfo.UpdateFunctions =  [codeInfo.UpdateFunctions, Core2_Task3_update_Interface];
  
;
          tmpArgs         = [];
  tmpActualArgs   = [];
  tmpRet          = coder.types.Argument.empty;
  tmpActualReturn = RTW.DataInterface.empty;
  
  
  Core2_Task4_output_Prototype            = coder.types.Prototype;
  Core2_Task4_output_Prototype.Arguments  = tmpArgs;
  Core2_Task4_output_Prototype.Return     = tmpRet;
  Core2_Task4_output_Prototype.HeaderFile = ['slexMulticoreExample', '.h'];
  Core2_Task4_output_Prototype.SourceFile = ['slexMulticoreExample', '.c'];
  
  Core2_Task4_output_Interface              = RTW.FunctionInterface;
  Core2_Task4_output_Interface.Prototype    = Core2_Task4_output_Prototype;
  Core2_Task4_output_Interface.ActualArgs   = tmpActualArgs;
  Core2_Task4_output_Interface.ActualReturn = tmpActualReturn;
  
  Core2_Task4_output_Prototype.Name = 'Core2_Task4_output'; 
  time_2 = codeInfo.TimingProperties(getIndexFromTimingInternalId(codeInfo.TimingInternalIds, 2));
  Core2_Task4_output_Interface.Timing = time_2;
  
      codeInfo.OutputFunctions =  [codeInfo.OutputFunctions, Core2_Task4_output_Interface];
  
;
   
            tmpArgs         = [];
  tmpActualArgs   = [];
  tmpRet          = coder.types.Argument.empty;
  tmpActualReturn = RTW.DataInterface.empty;
  
  
  Core2_Task4_update_Prototype            = coder.types.Prototype;
  Core2_Task4_update_Prototype.Arguments  = tmpArgs;
  Core2_Task4_update_Prototype.Return     = tmpRet;
  Core2_Task4_update_Prototype.HeaderFile = ['slexMulticoreExample', '.h'];
  Core2_Task4_update_Prototype.SourceFile = ['slexMulticoreExample', '.c'];
  
  Core2_Task4_update_Interface              = RTW.FunctionInterface;
  Core2_Task4_update_Interface.Prototype    = Core2_Task4_update_Prototype;
  Core2_Task4_update_Interface.ActualArgs   = tmpActualArgs;
  Core2_Task4_update_Interface.ActualReturn = tmpActualReturn;
  
  Core2_Task4_update_Prototype.Name = 'Core2_Task4_update'; 
  time_2 = codeInfo.TimingProperties(getIndexFromTimingInternalId(codeInfo.TimingInternalIds, 2));
  Core2_Task4_update_Interface.Timing = time_2;
  
      codeInfo.UpdateFunctions =  [codeInfo.UpdateFunctions, Core2_Task4_update_Interface];
  
;
    
    
  

    
      
      tmpArgs         = [];
tmpActualArgs   = [];
tmpRet          = coder.types.Argument.empty;
tmpActualReturn = RTW.DataInterface.empty;
  

  Terminate_Prototype = coder.types.Prototype;
  Terminate_Prototype.Arguments  = tmpArgs;
  Terminate_Prototype.Return     = tmpRet;
    Terminate_Prototype.HeaderFile = ['slexMulticoreExample', '.h'];
  Terminate_Prototype.SourceFile = ['slexMulticoreExample', '.c'];

  Terminate_Interface = RTW.FunctionInterface;
  Terminate_Interface.Prototype    = Terminate_Prototype;
  Terminate_Interface.ActualArgs   = tmpActualArgs;
  Terminate_Interface.ActualReturn = tmpActualReturn;

  time_constant = codeInfo.TimingProperties(getIndexFromTimingInternalId(codeInfo.TimingInternalIds, -1));
      Terminate_Interface.Timing = time_constant;
            Terminate_Prototype.Name = ['slexMulticoreExample_terminate'];
      codeInfo.TerminateFunctions =  [codeInfo.TerminateFunctions, Terminate_Interface'];


  



if ~isempty(skippedParameters)
codeInfo.Parameters(skippedParameters) = [];
end


% Handling Right-Click Builds
ss = rtwprivate('getSourceSubsystemHandle',codeInfo.GraphicalPath);
% Check if Rt-Click build, then re-map SIDs
if ~isempty(ss) && rtwprivate('rtwattic','hasSIDMap')
   codeInfo = modifyCodeInfoForSubsystemBuild(ss, codeInfo);
end

  lookupTableArray = [];         
  if exist('expInports', 'var')
    save codeInfo.mat codeInfo expInports lookupTableArray;
  else
    save codeInfo.mat codeInfo lookupTableArray;
  end
returnVal = 1;

% End Function: writeCodeInfoFcn

function data = uniquifyDataAccess(list)
  data = RTW.DataInterface.empty;
  for idx=1:numel(list)
      if ~isPresentDI(data, list(idx))
          data(end+1) = list(idx); %#ok<AGROW>
      end
  end
% End Function: uniquifyDataAccess
        
function isPresent = isPresentDI(list, di)
  isPresent = false;
  for idx = 1:numel(list)
    if isequal(list(idx), di)
      isPresent = true;
      break
    end
  end

function idx = getIndexFromTimingInternalId(internalIdVec, internalId)
 idx = find(internalIdVec == internalId);
 if (isempty(idx) || (length(idx) > 1))
    ciMsg = 'Time object cannot be empty'; 
    ciExc = MException('RTW:buildProcess:CodeInfoInternalError',ciMsg);
    throw(ciExc);
  end
% End Function: getIndexFromTimingInternalId

function checkDataGraphicalNames(ciName, rtwName)
  if (strcmp(ciName, rtwName) ~= 1)
    ciMsg = ['Name mismatch: ', ciName, ' and ', rtwName]; 
    ciExc = MException('RTW:buildProcess:CodeInfoInternalError',ciMsg);
    throw(ciExc);
  end
% End Function: checkDataGraphicalNames

function iData = getInternalDataByName(iDataVec, iDataName)
 iData = RTW.DataInterface.empty;
 for idxData = 1:numel(iDataVec)
    if strcmp(iDataName, iDataVec(idxData).GraphicalName)
       iData(end+1) = iDataVec(idxData);
       break
    end
 end
 if (isempty(iData) || (length(iData) > 1))
    ciMsg = 'Internal Data object cannot be empty'; 
    ciExc = MException('RTW:buildProcess:CodeInfoInternalError',ciMsg);
    throw(ciExc);
  end
% End Function: getInternalDataByName

function iData = getInternalDataByVariableName(iDataVec, iDataVariableName)
 iData = RTW.DataInterface.empty;
 for idxData = 1:numel(iDataVec)
    if strcmp(iDataVariableName, iDataVec(idxData).Implementation.VariableName)
       iData = iDataVec(idxData);
       break
    end
 end
 if isempty(iData)
    ciMsg = 'Internal Data object cannot be empty'; 
    ciExc = MException('RTW:buildProcess:CodeInfoInternalError',ciMsg);
    throw(ciExc);
  end
% End Function: getInternalDataByVariableName

function paramIndex = getParamIndexFromGraphicalName(iParamVec, graphicalName)
  paramIndex = [];
  for idxData = 1:numel(iParamVec)
    if strcmp(graphicalName, iParamVec(idxData).GraphicalName)
       paramIndex = idxData;
       break
    end
  end
% End Function: getParamIndexFromGraphicalName

function codeInfo = modifyCodeInfoForSubsystemBuild(ss, codeInfo)
    
% Extract Subsystem Build Map from AtticData
    Subsystem_Build_Mapping = rtwprivate('rtwattic','getSIDMap');

% Parameters
    for i = 1:length(codeInfo.Parameters)
        sid = codeInfo.Parameters(i).SID;        

        sid = Simulink.ID.getSubsystemBuildSID(sid,ss, Subsystem_Build_Mapping);
        codeInfo.Parameters(i).SID = sid;        
    end
    
% Data Stores
     for i = 1:length(codeInfo.DataStores)
         sid = codeInfo.DataStores(i).SID;         

         sid = Simulink.ID.getSubsystemBuildSID(sid,ss, Subsystem_Build_Mapping);
         codeInfo.DataStores(i).SID = sid;
     end
    
% Inports
    for i = 1:length(codeInfo.Inports)
        sid = codeInfo.Inports(i).SID;
        
        sid = Simulink.ID.getSubsystemBuildSID(sid,ss, Subsystem_Build_Mapping);
        codeInfo.Inports(i).SID = sid;
    end
    
% Outports
    for i = 1:length(codeInfo.Outports)
        sid = codeInfo.Outports(i).SID;
 
        sid = Simulink.ID.getSubsystemBuildSID(sid,ss, Subsystem_Build_Mapping);
        codeInfo.Outports(i).SID = sid;
    end    
   
